package Acme::CPANLists::Import::PerlAdvent::2006_12_15;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2006/15/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"File::HomeDir"}],summary=>"Modules mentioned in Perl Advent Calendar 2006 (day 15)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2006 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2006/15/> (retrieved on 2016-11-07). Visit the URL for the full contents.

