package Acme::CPANLists::Import::PerlAdvent::2006;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2006/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Devel::FastProf"},{module=>"Devel::SmallProf"},{module=>"File::Find::Iterator"},{module=>"File::Find::Object"},{module=>"File::Find::Rule"},{module=>"File::Finder"},{module=>"Text::CSV"},{module=>"Treemap"},{module=>"XML::Simple"},{module=>"CGI::Minimal"},{module=>"CGI::Simple"},{module=>"HTML::Template"},{module=>"File::Next"},{module=>"Module::Starter"},{module=>"Acme::Don::t"},{module=>"File::SortedSeek"},{module=>"Carp"},{module=>"Devel::ptkdb"},{module=>"Fatal"},{module=>"Graphics::ColorNames"},{module=>"Shell"},{module=>"Shell::Autobox"},{module=>"IPC::Run3"},{module=>"File::HomeDir"},{module=>"Math::ErrorPropagation"},{module=>"Math::Symbolic"},{module=>"Math::Symbolic::Custom::Contains"},{module=>"Math::SymbolicX::Inline"},{module=>"Number::Uncertainty"},{module=>"Number::WithError"},{module=>"Params::Util"},{module=>"Test::LectroTest"},{module=>"prefork"},{module=>"Log::Dispatch::FileRotate"},{module=>"Logfile::Rotate"},{module=>"Algorithm::Diff"},{module=>"Text::Diff"},{module=>"XML::Feed"},{module=>"Date::Calc"},{module=>"Devel::Cover"},{module=>"Pod::Coverage"},{module=>"Apache::PAR"},{module=>"PAR::Dist"},{module=>"PAR::Dist::FromCPAN"},{module=>"PAR::Dist::InstallPPD"},{module=>"criticism"},{module=>"DBD::AnyData"},{module=>"DateTime::Calendar::Discordian"}],summary=>"Modules mentioned in Perl Advent Calendar 2006"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2006

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2006/> (retrieved on 2016-11-07). Visit the URL for the full contents.

