package Acme::CPANLists::Import::PerlAdvent::2006_12_16;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2006/16/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Math::ErrorPropagation"},{module=>"Math::Symbolic"},{module=>"Math::Symbolic::Custom::Contains"},{module=>"Math::SymbolicX::Inline"},{module=>"Number::Uncertainty"},{module=>"Number::WithError"},{module=>"Params::Util"},{module=>"Test::LectroTest"},{module=>"prefork"}],summary=>"Modules mentioned in Perl Advent Calendar 2006 (day 16)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2006 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2006/16/> (retrieved on 2016-11-07). Visit the URL for the full contents.

