package Acme::CPANLists::Import::PerlAdvent::2006_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2006/19/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"XML::Feed"}],summary=>"Modules mentioned in Perl Advent Calendar 2006 (day 19)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2006 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2006/19/> (retrieved on 2016-11-07). Visit the URL for the full contents.

