#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2006',
                url => "http://perladvent.org/2006/",
                extract_urls => [map {"http://perladvent.org/2006/$_/"} 1..25],
                summary => 'Modules mentioned in Perl Advent Calendar 2006',
            },
            {
                name => '2006_12_01',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 1)",
                url => "http://perladvent.org/2006/1/",
            },
            {
                name => '2006_12_02',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 2)",
                url => "http://perladvent.org/2006/2/",
            },
            {
                name => '2006_12_03',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 3)",
                url => "http://perladvent.org/2006/3/",
            },
            {
                name => '2006_12_04',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 4)",
                url => "http://perladvent.org/2006/4/",
            },
            {
                name => '2006_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 5)",
                url => "http://perladvent.org/2006/5/",
            },
            {
                name => '2006_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 6)",
                url => "http://perladvent.org/2006/6/",
                add_modules => ['App::XLSperl'],
            },
            {
                name => '2006_12_07',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 7)",
                url => "http://perladvent.org/2006/7/",
            },
            {
                name => '2006_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 8)",
                url => "http://perladvent.org/2006/8/",
            },
            {
                name => '2006_12_09',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 9)",
                url => "http://perladvent.org/2006/9/",
            },
            {
                name => '2006_12_10',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 10)",
                url => "http://perladvent.org/2006/10/",
            },
            {
                name => '2006_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 11)",
                url => "http://perladvent.org/2006/11/",
            },
            {
                name => '2006_12_12',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 12)",
                url => "http://perladvent.org/2006/12/",
                # unspecific url
                add_modules => ['Pod::Usage'],
            },
            {
                name => '2006_12_13',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 13)",
                url => "http://perladvent.org/2006/13/",
            },
            {
                name => '2006_12_14',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 14)",
                url => "http://perladvent.org/2006/14/",
            },
            {
                name => '2006_12_15',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 15)",
                url => "http://perladvent.org/2006/15/",
            },
            {
                name => '2006_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 16)",
                url => "http://perladvent.org/2006/16/",
            },
            {
                name => '2006_12_17',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 17)",
                url => "http://perladvent.org/2006/17/",
            },
            {
                name => '2006_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 18)",
                url => "http://perladvent.org/2006/18/",
            },
            {
                name => '2006_12_19',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 19)",
                url => "http://perladvent.org/2006/19/",
            },
            {
                name => '2006_12_20',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 20)",
                url => "http://perladvent.org/2006/20/",
            },
            {
                name => '2006_12_21',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 21)",
                url => "http://perladvent.org/2006/21/",
            },
            {
                name => '2006_12_22',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 22)",
                url => "http://perladvent.org/2006/22/",
            },
            {
                name => '2006_12_23',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 23)",
                url => "http://perladvent.org/2006/23/",
            },
            {
                name => '2006_12_24',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 24)",
                url => "http://perladvent.org/2006/24/",
            },
            {
                name => '2006_12_25',
                summary => "Modules mentioned in Perl Advent Calendar 2006 (day 25)",
                url => "http://perladvent.org/2006/25/",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
